# Generated by Django 4.2.7 on 2023-11-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_id", models.CharField(max_length=50)),
                ("original_image", models.CharField(blank=True, max_length=500)),
                ("thumbnail", models.CharField(blank=True, max_length=500)),
                ("is_nsfw", models.BooleanField(default=False)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("creator_name", models.CharField(blank=True, default="", max_length=255)),
                ("creator_username", models.CharField(blank=True, default="", max_length=255)),
                ("caption", models.TextField(blank=True, default="")),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
