# Generated by Django 4.2.7 on 2023-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waifu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordWebhook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("server_name", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField()),
                ("interval", models.IntegerField(default=5)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
