# Generated by Django 4.2.7 on 2024-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waifu", "0003_telegramuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="blurhash",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
