# Generated by Django 4.2.14 on 2024-10-06 04:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tiktok", "0002_savedtiktokvideo_tiktok_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ("username",
                 models.CharField(help_text="Should have prefix `@`", max_length=255, unique=True)),
                ("nickname", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("followers", models.PositiveIntegerField(default=0)),
                ("following", models.PositiveIntegerField(default=0)),
                ("visible_content_count", models.PositiveIntegerField(default=0)),
                ("avatar_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
