# Generated by Django 4.2.14 on 2024-10-06 16:27

from django.db import migrations, models
import tiktok.models


class Migration(migrations.Migration):

    dependencies = [
        ("tiktok", "0004_alter_user_avatar_url_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_file",
            field=models.ImageField(
                blank=True, null=True, upload_to=tiktok.models.tiktok_profile_picture_upload_location
            ),
        ),
    ]
