# Generated by Django 4.2.7 on 2024-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(max_length=150, primary_key=True, serialize=False)),
                ("profil_picture_url", models.URLField(max_length=500)),
                ("api_updated_time", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
