# Generated by Django 4.2.7 on 2024-07-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="api_updated_time",
        ),
        migrations.AddField(
            model_name="user",
            name="updated_from_api_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Update from API datetime"),
        ),
    ]
