# Generated by Django 4.2.7 on 2024-06-28 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_updated_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 28, 6, 3, 21, 231422, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
