# Generated by Django 4.2.7 on 2024-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_alter_user_username_instaloader"),
    ]

    operations = [
        migrations.AddField(
            model_name="instaloader",
            name="is_login_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instaloader",
            name="last_login_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
