# Generated by Django 4.2.7 on 2024-06-28 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_alter_user_api_updated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="follower_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="api_updated_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="API Updated Time"),
        ),
    ]
