# Generated by Django 4.2.7 on 2024-07-02 09:22

from django.db import migrations, models
import instagram.utils


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0004_user_biography_user_follower_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to=instagram.utils.user_profile_picture_upload_location
            ),
        ),
    ]
