# Generated by Django 4.2.14 on 2024-09-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0005_user_instagram_id_alter_user_profile_picture_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Instaloader",
        ),
    ]
