# Generated by Django 4.2.7 on 2024-07-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0005_user_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profil_picture_url",
            new_name="profile_picture_url",
        ),
    ]
