# Generated by Django 4.2.7 on 2024-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0006_rename_profil_picture_url_user_profile_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_updated_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="API Updated Time"),
        ),
    ]
