# Generated by Django 4.2.14 on 2024-09-24 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0006_delete_instaloader"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoastingLog",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("user_data", models.JSONField()),
                ("roasting_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
