# Generated by Django 4.2.7 on 2024-07-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0007_alter_user_api_updated_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("story_id", models.CharField(max_length=50)),
                ("thumbnail_url", models.URLField(max_length=500)),
                ("media_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("story_created_at", models.DateTimeField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="instagram.user")),
            ],
        ),
    ]
