# Generated by Django 4.2.14 on 2024-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0007_roastinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_auto_update_stories",
            field=models.BooleanField(default=False),
        ),
    ]
