# Generated by Django 4.2.14 on 2024-11-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0008_user_allow_auto_update_stories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(blank=True, related_name="followers_set", to="instagram.user"),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(blank=True, related_name="following_set", to="instagram.user"),
        ),
    ]
