# Generated by Django 4.2.7 on 2024-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0008_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="media_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="story",
            name="thumbnail_url",
            field=models.URLField(max_length=1000),
        ),
    ]
