# Generated by Django 4.2.7 on 2024-07-04 08:10

from django.db import migrations, models
import instagram.utils


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0009_alter_story_media_url_alter_story_thumbnail_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name": "Story", "verbose_name_plural": "Stories"},
        ),
        migrations.AddField(
            model_name="story",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to=instagram.utils.user_stories_upload_location),
        ),
        migrations.AddField(
            model_name="story",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=instagram.utils.user_stories_upload_location),
        ),
    ]
