# Generated by Django 4.2.14 on 2024-11-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0009_userfollowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowing",
            name="instagram_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
