# Generated by Django 4.2.14 on 2024-11-08 04:26

from django.db import migrations, models
import django.db.models.deletion
import instagram.mixins
import instagram.utils


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0010_userfollowing_instagram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instagram_id", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("profile_picture_url", models.URLField(max_length=1000)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to=instagram.utils.user_following_profile_picture_upload_location
                    ),
                ),
                ("is_private_account", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="follower", to="instagram.user"
                    ),
                ),
            ],
            bases=(models.Model, instagram.mixins.URLToFileFieldMixin),
        ),
    ]
