# Generated by Django 4.2.7 on 2024-07-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0010_alter_story_options_story_media_story_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="id",
        ),
        migrations.AlterField(
            model_name="story",
            name="story_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
