# Generated by Django 4.2.14 on 2024-11-10 04:42

from django.db import migrations, models
import instagram.utils


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0011_userfollower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollower",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to=instagram.utils.user_follower_profile_picture_upload_location
            ),
        ),
    ]
