name: Deployment

on:
  release:
    types: [published]

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Remote SSH Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          port: 22
          command_timeout: 1337m
          script_stop: true
          script: |
            cd ${{ secrets.REPOSITORY_LOCATION }}
            git pull origin master --force
            docker compose -f production.yml build
            docker compose -f production.yml up -d
            docker compose -f production.yml run --rm django python manage.py migrate
            docker builder prune --force
