# Generated by Django 4.2.7 on 2024-03-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterDownloaderSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_maintenance", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Twitter Downloader Setting",
            },
        ),
    ]
