# Generated by Django 4.2.7 on 2024-03-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0002_twitterdownloadersetting"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TwitterDownloaderSetting",
            new_name="TwitterDownloaderSettings",
        ),
    ]
