# Generated by Django 4.2.7 on 2024-03-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0004_alter_twitterdownloadersettings_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TwitterDownloaderSettings",
            new_name="Settings",
        ),
    ]
