# Generated by Django 4.2.7 on 2024-03-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0005_rename_twitterdownloadersettings_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadedTweet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tweet_url", models.URLField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="twitter_downloader.telegramuser"
                    ),
                ),
            ],
        ),
    ]
