# Generated by Django 4.2.7 on 2024-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0012_alter_downloadedtweet_tweet_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="request_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
