# Generated by Django 4.2.7 on 2024-06-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0014_externallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallink",
            name="is_web_app",
            field=models.BooleanField(default=False),
        ),
    ]
