# Generated by Django 4.2.7 on 2024-06-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0015_externallink_is_web_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadedtweet",
            name="tweet_url",
            field=models.URLField(max_length=500),
        ),
    ]
