# Generated by Django 4.2.14 on 2024-10-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_downloader", "0017_alter_telegramuser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="secret_token",
            field=models.CharField(blank=True),
        ),
    ]
